import type { Metadata } from "next";
import { Open_Sans, Poppins, Volkhov } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const openSans = Open_Sans({
  weight: ['400', '500', '600', '700'],
  style: 'normal',
  subsets: ["latin"],
  display: 'swap'
});

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  style: 'normal',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins'
})

const volkhov = Volkhov({
  weight: ['700'],
  style: 'normal',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-valkhov'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.className} ${poppins.variable} ${volkhov.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
